### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by QianWanghhu** [sandialabs/pyapprox#1]
While installing the package to my computer, I have met two issues:
(1) “C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\HostX86\x64\cl.exe” /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IF:\Anaconda3\envs\approxi\include -IF:\Anaconda3\envs\approxi\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcpyapprox/cython\sparse_grid.c /Fobuild\temp.win-amd64-3.7\Release\pyapprox/cython\sparse_grid.obj

The solution worked for my computer is adding include_dirs=[np.get_include()] to the setuptools.setup in setup file.

(2) The module torch installed through setup.py was not working. 
 Instead, I installed separately from PyTorch through the PyTorch website following the instruction online.

Hope this will be helpful for others and these issues will be fixed soon.

**Comment by jdjakem** [comment]
The installation procedure has been updated and should fix this issue.
