### ISSUE TITLE
Undefined function used in utilities.py

### ISSUE THREAD

**Issue by ConnectedSystems** [sandialabs/pyapprox#7]
At various locations in `utilities.py` the function `total_degree_subspace_dimension()` is called, but is not defined or imported 

https://github.com/sandialabs/pyapprox/blob/0dabe4fdb8c9653d7eabb88e04d9581e36c00b78/pyapprox/utilities.py#L452

**Comment by jdjakem** [comment]
Fixed with commit 0d024bdbe929c5ac56457dd6b68c1564a06f12b6 on package_restructure branch
